server:
  port: 8080
  contextPath: /admin

spring:
  datasource:
    username: zero
    password: one
    url: jdbc:mysql://localhost:3306/search_engine?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changeset/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static/
externaldata:
  site-array:
#    - url: http://www.playback.ru
#      name: Интернет-магазин
#    - url: https://ipfran.ru
#      name: ИПФ РАН
#    - url: http://radiomv.ru
#      name: радио
#    - url: https://volochek.life
#      name: Вышний Волочек
#    - url: https://dombulgakova.ru
#      name: Булгаковский дом
#    - url: https://nikoartgallery.com
#      name: Галерея Никогосяна
    - url: https://www.svetlovka.ru
      name: ЦГМБ им.М.А.Светлова

